r:
	src/main.out
v:
	xdg-open doc/main.pdf
pdf:
	pdflatex -output-directory=doc main.tex
0:
	g++ -o src/main.out src/main0.cpp 
1:
	g++ -o src/main.out src/main1.cpp
2:
	g++ -o src/main.out src/main2.cpp 
etex:
	nvim doc/main.tex
ecpp:
	nvim src/*.cpp
